### PR TITLE
Nuget package

### LINKED ISSUE #920: Create nuget package to facilitate building against ebpf-for-windows
Create nuget package to facilitate building against ebpf-for-windows.

This would make it easier for developers to consume the ebpf-for-windows APIs without having to first build them.

### PR DESCRIPTION
**Pull request by dthaler**
## Description

Create a developer nuget package containing the files needed to build ebpf programs and applications.

The nuget package has includes from external/* in a different path so this PR also changes includes paths so the paths are not hard coded in other .h files.

The nuget package built by this PR is currently up on nuget.org for testing: https://www.nuget.org/packages/eBPF-for-Windows/

The following L3AF PR consumes the nuget package built by this PR: https://github.com/l3af-project/eBPF-Package-Repository/pull/17

Fixes #920

## Testing

Tested using the L3AF PR linked above, where one can see the build check complete.  The demo repo should do likewise.

## Documentation

Minimal README.md file only.   This will be updated in a future PR once other improvements are available and integration with L3AF and the Demo repos are done and any feedback from those experiences incorporated.

### CODE REVIEW

**Comment by Alan-Jowett** [comment]
One suggestion:
Now that #994 is merged, can we include the scripts and binaries necessary to generate native images in the nuget package as well?

**Review by Alan-Jowett — DISMISSED** [review]

**Comment by Alan-Jowett** [comment]
> One suggestion: Now that #994 is merged, can we include the scripts and binaries necessary to generate native images in the nuget package as well?

It should only require (in addition to files you have already incuded):
bpf2c.exe
Convert-BpfToNative.ps1
tools\bpf2c\*

**Comment by Alan-Jowett** [comment]
> > > One suggestion: Now that #994 is merged, can we include the scripts and binaries necessary to generate native images in the nuget package as well?
> > 
> > 
> > It should only require (in addition to files you have already incuded): bpf2c.exe Convert-BpfToNative.ps1 tools\bpf2c*
> 
> bpf2c.exe is already included, but I can include anything else we need in a separate PR, or this one if critical.

Not critical, I can add it in a later PR.

**Comment by dthaler** [comment]
> > > > One suggestion: Now that #994 is merged, can we include the scripts and binaries necessary to generate native images in the nuget package as well?
> > > 
> > > 
> > > It should only require (in addition to files you have already incuded): bpf2c.exe Convert-BpfToNative.ps1 tools\bpf2c*
> > 
> > 
> > bpf2c.exe is already included, but I can include anything else we need in a separate PR, or this one if critical.
> 
> Not critical, I can add it in a later PR.

I needed to rebase and resolve conflicts, so I at least added the ps1 script.  You will need to add whatever else in a later PR since I am not quite sure the exact set needed.

**Review by Alan-Jowett — APPROVED** [review]

**Review by saxena-anurag — APPROVED** [review]

**Pull request merged**
