### PR TITLE
Retry failed FwpmTransactionBegin

### LINKED ISSUE #3602: Workflow failed - km_mt_stress_tests_restart_extension
[Failed Run](https://github.com/microsoft/ebpf-for-windows/actions/runs/9336770229)
[Codebase](https://github.com/microsoft/ebpf-for-windows/tree/05a71895566eac26a9032aac6426f58f6fa5b6de)
Test name - `km_mt_stress_tests_restart_extension`

### PR DESCRIPTION
**Pull request by dv-msft**
## Description

WFP allows only 1 active transaction at a time per WFP session.  This leads to errors in multi-threaded scenarios where threads simultaneously try to load and attach ebpf program types supported by the NetEbpfExt extension.  In certain timing sensitive instances, such multi-threaded scenarios cause NetEbpfExt to attempt to create a new WFP transaction while a previous transaction is still in progress.

This PR adds time-bounded retry logic to the call to `FwpmTransactionBegin` call to allow for an already-in-progress transaction (if any) to complete.

## Testing

Fix verified locally (100% repro) as well as multiple, back-to-back CI/CD runs on private self-hosted runner.

_Do any existing tests cover this change? Are new tests needed?_
Issue uncovered by existing tests.  No new tests needed.

## Documentation

No Documentation changes needed.

## Installation

_Is there any installer impact for this change?_
No Installer impact.

Fixes #3602 #3607

### CODE REVIEW

**Review by shankarseal — CHANGES_REQUESTED** [review]
Instead of retry logic, a different session must be used for a given program attach operation.

**Comment by dv-msft** [comment]
> Instead of retry logic, a different session must be used for a given program attach operation.

Did not work.  Will discuss offline.

**Comment by saxena-anurag** [comment]
Will this issue be amplified when we support multiple programs to be attached to the same hook?

**Comment by Alan-Jowett** [comment]
Waiting on Shankar's comments to be addressed. Will review after that.

**Comment by shankarseal** [comment]
This is being abandoned as this not the right fix.

**Pull request closed without merging**
