### PR TITLE
chore: fix the hash for setup scripts

### PR DESCRIPTION
**Pull request by feiskyer**
## Description

chore: fix the hash for setup scripts, orelse scripts/Setup-DevEnv.ps1 would always fail.

## Testing

_Do any existing tests cover this change? Are new tests needed?_

## Documentation

_Is there any documentation impact for this change?_

## Installation

_Is there any installer impact for this change?_

### CODE REVIEW

**Review by Alan-Jowett — APPROVED** [review]

**Review by gtrevi — APPROVED** [review]

**Comment by feiskyer** [comment]
@Alan-Jowett  @gtrevi thanks for reviewing. any chances to get this merged?

**Review by rectified95 — CHANGES_REQUESTED** [review]
I'm getting a different hash value, are you sure you got this right?
61A62681079ADD48F3B2F27533EEADDABADA9E119D1D9B4764F9AC497DF25FA4

**Comment by feiskyer** [comment]
@rectified95 are you getting it from this PR? the file contents are changes as part this PR

**Review by rectified95 — APPROVED** [review]
You're right, the new hash is correct, thanks!

**Comment by rectified95** [comment]
We're seeing intermittent CI failures, most likely due to incomplete deployment of a recent CRT runtime fix on the GH runners. @feiskyer we'll merge your PR when it goes away - PR just got booted from the merge queue due to failed checks :(

**Pull request merged**
