### PR TITLE
Test error fix

### LINKED ISSUE #2707: CI/CD jobs can succeed despite test failures.
### Describe the bug

1. There are a few PRs for which the pipeline shows a passing run, even though their logs contain test failures.
Ex. https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646
```
bindmonitor_tailcall_native_test
-------------------------------------------------------------------------------
D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp([64](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:65)4)
...............................................................................

D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(624): FAILED:
  REQUIRE( perform_bind(&sockets[0], 30000) == 0 )
with expansion:
  -1 == 0

[12:54:44] :: api_test.exe Passed
```
I've also seen an example of this in some other test, which might mean this is not test-specific. 
Have we added any indirection test invocation and result gathering?

2. Crash dumps are not always picked up by the respective job.
From the same run as above:
```
[12:52:40] :: Executing api_test.exe
[12:52:40] :: C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe -q --modules=C:\eBPF --export_type binary:api_test.exe.cov -- api_test.exe
[12:54:31] :: Generation of crash dump succeeded
Error: [12:54:41] :: [error] 

----------------------------------------------------
*** Your application has thrown an unhandled exception. Code: 32[21](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:22)[22](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:23)5477: EXCEPTION_ACCESS_VIOLATION
----------------------------------------------------
See https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#your-application-has-thrown-an-unhandled-exception-code-3221225477-exception_access_violation for additional information.

Error: [12:54:44] :: [error] Your program stop with error code: -2147483645
```
Then during the step 'Check for crash dumps':
`These files don't exist: c:/dumps/x64/Debug/*.dmp`

### OS information

_No response_

### Steps taken to reproduce bug

run the CI

### Expected behavior

CI runs never show up as successful when their components fail.

### Actual outcome

CI runs sometimes show up as successful when their components fail.

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by rectified95**
## Description

Fixes #2707 
The failure condition was checking if the $LASTEXITCODE was set by the failed test or if the second to last word of output contained the word "failed".

Turns out Catch2 doesn't set the exit code to non-zero when a test fails.
Also, the assumption about log output didn't hold for ConnectRedirect test - it prints one extra line "Cleaning up Winsock".
Instead, checking line N-2. 

For api_test, there was an anomalous case where the test failed haflway through, and didn't print the final summary, so doing a full case-sentisitve scan of the log output for the string "FAILED:" to match Catch2 output.

## Testing

Forced a failure of both the tests and saw the code detected it.

### CODE REVIEW

**Comment by saxena-anurag** [comment]
>> For api_test, there was an anomalous case where the test failed haflway through, and didn't print the final summary, so doing a full case-sentisitve scan of the log output for the string "FAILED:" to match Catch2 output.

nit: Do we know which test case failure causes this behavior?

**Comment by rectified95** [comment]
```
Run .\execute_ebpf_cicd_tests.ps1
[12:52:38] :: Running eBPF CI/CD tests on vm1
[12:52:40] :: Executing api_test.exe
[12:52:40] :: C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe -q --modules=C:\eBPF --export_type binary:api_test.exe.cov -- api_test.exe
[12:54:31] :: Generation of crash dump succeeded
Error: [12:54:41] :: [error] 

----------------------------------------------------
*** Your application has thrown an unhandled exception. Code: 3221225477: EXCEPTION_ACCESS_VIOLATION
----------------------------------------------------
See https://github.com/OpenCppCoverage/OpenCppCoverage/wiki/FAQ#your-application-has-thrown-an-unhandled-exception-code-3221225477-exception_access_violation for additional information.

Error: [12:54:44] :: [error] Your program stop with error code: -2147483645
[12:54:44] :: 

[12:54:44] :: Randomness seeded to: 1008009701
_native_module_helper::get_file_name: droppacket968522c1-dc48-4c4d-9e99-844911f97117.sys
_native_module_helper::get_file_name: bindmonitora608d418-f298-4446-9ff4-73c[16](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:17)370672e.sys
_native_module_helper::get_file_name: droppacketc485141c-023c-4261-97c3-a37c0abbfa6d.sys
_native_module_helper::get_file_name: bindmonitorc8aa5c30-0266-4a10-a465-85394528a75a.sys

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
api_test.exe is a Catch2 v3.4.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
ringbuf_api_jit
-------------------------------------------------------------------------------
D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(464)
...............................................................................

D:\a\ebpf-for-windows\ebpf-for-windows\tests\libs\common\common_tests.cpp([20](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:21)6): FAILED:
  REQUIRE( ring_buffer_event_callback.wait_for(1s) == std::future_status::ready )
with expansion:
  1 == 0

-------------------------------------------------------------------------------
ringbuf_api_interpret
-------------------------------------------------------------------------------
D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(469)
...............................................................................

D:\a\ebpf-for-windows\ebpf-for-windows\tests\libs\common\common_tests.cpp(206): FAILED:
  REQUIRE( ring_buffer_event_callback.wait_for(1s) == std::future_status::ready )
with expansion:
  1 == 0

-------------------------------------------------------------------------------
bindmonitor_tailcall_native_test
-------------------------------------------------------------------------------
D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(644)
...............................................................................

D:\a\ebpf-for-windows\ebpf-for-windows\tests\api_test\api_test.cpp(6[24](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:25)): FAILED:
  REQUIRE( perform_bind(&sockets[0], [30](https://github.com/microsoft/ebpf-for-windows/actions/runs/5672733794/job/15373312646#step:19:31)000) == 0 )
with expansion:
  -1 == 0


[12:54:44]] :: api_test.exe Passed
```

**Comment by rectified95** [comment]
@saxena-anurag See logs above - it's unclear to me which test case that was. OpenCppCoverage.exe surfaced info on crash dump generation, but our jobs weren't able to pick it up in the later stages.
Link to the job in the issue.

**Comment by saxena-anurag** [comment]
> @saxena-anurag See logs above - it's unclear to me which test case that was. OpenCppCoverage.exe surfaced info on crash dump generation, but our jobs weren't able to pick it up in the later stages. Link to the job in the issue.

Thanks for the info. It looks like there was a dump filed for the above exception. Do you know if there is bug filed for that crash.

**Review by gtrevi — APPROVED** [review]

**Review by dthaler — APPROVED** [review]

**Comment by rectified95** [comment]
@saxena-anurag I don't think there'd a bug for that crash or test failure, because our jobs didn't register a crash dump - perhaps opencppcoverage.exe put the dump somewhere we don't look?
The test failed, but we didn't even mark the job as failed - that's how I first picked up on the hidden failures. So

**Pull request merged**
