### PR TITLE
WIP: Testing update to build instructions.

### PR DESCRIPTION
**Pull request by hawkinsw**
**WIP** **WIP** **WIP**

Do not merge.

**WIP** **WIP** **WIP**

### CODE REVIEW

**Comment by rectified95** [comment]
@hawkinsw I canceled your CI run - external contributors are not supposed to be able launch our CI workflows without prior PR approval. We need to understand if this is a GH bug

**Comment by hawkinsw** [comment]
@rectified95 I am working with @Alan-Jowett on ubpf and we are testing some changes there to the build system that will require changes to the CI/CD pipeline (and build instructions) on ebpf-for-windows. This PR was my attempt to sanity check those changes before I submitted an official PR. I think that things progressed far enough for me to verify that my fix will work. I will convert this to a full PR on Monday when @Alan-Jowett is back online!

Have a great weekend!

**Comment by gtrevi** [comment]
@hawkinsw could you please move this to draft, until WIP?

**Comment by hawkinsw** [comment]
> @hawkinsw could you please move this to draft, until WIP?

Of course! Sorry if I was spamming you! I was working with @Alan-Jowett on getting a few things tested.

**Comment by hawkinsw** [comment]
We have significantly changed how we are handling/building the external projects in ubpf that caused this to be a problem. As a result, we no longer need this PR.

**Pull request closed without merging**
