### PR TITLE
Make skip-duplicate-actions optional.

### PR DESCRIPTION
**Pull request by Alan-Jowett**
## Description

Invoking reusable-build from the netperf workflow, it fails to execute if the target repo is unchanged. 

## Testing

CI/CD

## Documentation

No.

## Installation

No.

### CODE REVIEW

**Review by dthaler — COMMENTED** [review]
Can you provide more information about what problem this fixes?
Skipping duplicate actions is a perf improvement, so what problem does slowing down the build solve?

**Comment by Alan-Jowett** [comment]
> Can you provide more information about what problem this fixes? Skipping duplicate actions is a perf improvement, so what problem does slowing down the build solve?

This is an example of the issue it causes:
https://github.com/microsoft/netperf/actions/runs/8426243685/job/23074138884

Because the build is skipped, the artifacts aren't present to run the performance tests.

**Comment by Alan-Jowett** [comment]
It should be possible to use:
https://github.com/fkirc/skip-duplicate-actions?tab=readme-ov-file#do_not_skip 

But it doesn't support filtering on repository_dispatch. As per the docs, the only permissible values are:
```
do_not_skip
A JSON-array with triggers that should never be skipped.

Possible values are pull_request, push, workflow_dispatch, schedule, release, merge_group.

Default: '["workflow_dispatch", "schedule", "merge_group"]'
```

**Comment by Alan-Jowett** [comment]
Reactivating as the proposed work-around doesn't work.

The fkirc/skip-duplicate-actions action examines the history of the calling repo, not the repo in which the build is being performed.

Chain is as follows:
Microsoft/ebpf-for-windows performs a "repository_dispatch" to run the Microsoft/netperf ebpf.yml
The Microsoft/netperf's ebpf.yml calls the Microsoft/ebpf-for-windows's reusable-build.yml.
The fkirc/skip-duplicate-actions then checks if a build has been performed for the commit in Microsoft/netperf instead of Microsoft/ebpf-for-windows.

Net effect is that the build is always skipped, even if Microsoft/ebpf-for-windows contains changes.

**Comment by Alan-Jowett** [comment]
> Can you provide more information about what problem this fixes? Skipping duplicate actions is a perf improvement, so what problem does slowing down the build solve?

Problem being solved:
The step fkirc/skip-duplicate-actions looks for changes in the wrong repo, incorrectly skipping builds even when changes are present.

**Review by gtrevi — APPROVED** [review]

**Review by dv-msft — APPROVED** [review]

**Pull request merged**
