### PR TITLE
Add basic regression test for 0.9.0

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description

This PR adds a basic regression test for loading and attaching a native sock_addr eBPF program with version 0.9.0.

## Testing

This PR adds test.

## Documentation

NA

### CODE REVIEW

**Review by dthaler — COMMENTED** [review]
Why does this PR include binaries?
Checking in binaries causes code scanning alerts like this one: https://github.com/microsoft/ebpf-for-windows/security/code-scanning/485

**Comment by saxena-anurag** [comment]
> Why does this PR include binaries? Checking in binaries causes code scanning alerts like this one: [Binary-Artifacts](/microsoft/ebpf-for-windows/security/code-scanning/485)

Binaries are added in the PR to run the test against 0.9 release artifacts.

**Comment by gtrevi** [comment]
@saxena-anurag Added released binary artifacts to the Release: https://github.com/microsoft/ebpf-for-windows/releases/download/v0.9.0/Build-x64-native-only-Release.0.9.0.zip

**Comment by dthaler** [comment]
> > Why does this PR include binaries? Checking in binaries causes code scanning alerts like this one: [Binary-Artifacts](/microsoft/ebpf-for-windows/security/code-scanning/485)
> 
> Binaries are added in the PR to run the test against 0.9 release artifacts.

You don't need to check in binaries to do that.  E.g., you can download them as part of the CICD step.

**Comment by saxena-anurag** [comment]
> > > Why does this PR include binaries? Checking in binaries causes code scanning alerts like this one: [Binary-Artifacts](/microsoft/ebpf-for-windows/security/code-scanning/485)
> > 
> > 
> > Binaries are added in the PR to run the test against 0.9 release artifacts.
> 
> You don't need to check in binaries to do that. E.g., you can download them as part of the CICD step.

Yes I am planning to do that only. Will push the update soon.

**Review by dthaler — APPROVED** [review]

**Pull request merged**
