### PR TITLE
Fix xdp_md struct name

### LINKED ISSUE #3128: Change of struct name from xdp_md to xdp_md_ breaks eBPF programs that assume older name
PR #3040 changed the name of the xdp_md struct from `xdp_md` to `xdp_md_` (in ebpf_nethooks.h).
That breaks build for any eBPF program which was assuming `xdp_md` as the struct name.

### PR DESCRIPTION
**Pull request by saxena-anurag**
Fixes #3128

## Description

Fixes the xdp_md struct name.

## Testing

Manually tested programs which were dependent on older name.

## Documentation

NA

## Installation

No.

### CODE REVIEW

**Review by gtrevi — APPROVED** [review]

**Comment by mtfriesen** [comment]
I think @matthewige intentionally mangled the name so this wouldn't conflict with definitions in the xdp-for-windows repo.

**Review by dthaler — APPROVED** [review]

**Comment by mtfriesen** [comment]
Ah, Matt is OOF for the holidays. His PR #3040 renamed this struct, and I believe the intention was to define the "real" struct in xdp-for-windows.

**Review by mtfriesen — CHANGES_REQUESTED** [review]
Please define this struct in xdp-for-windows.

**Comment by saxena-anurag** [comment]
Closing the PR for now.

**Pull request closed without merging**
