### PR TITLE
Add process_id to sock_addr_ctx

### PR DESCRIPTION
**Pull request by saxena-anurag**
## Description

This PR adds `process_id` field to `sock_addr_ctx` context structure which is passed to sock_addr eBPF program.

## Testing

Adds tests to validate the process ID passed to eBPF program.

## Documentation

NA

### CODE REVIEW

**Comment by dthaler** [comment]
Why add it to ctx instead of providing via a generic helper function?   Seems like adding it to the ctx doesn't scale as well to many prog types.   If Linux does it in the ctx then cross-plat portability is a good reason to put it in the ctx.

**Review by dthaler — COMMENTED** [review]
Why add it to ctx instead of providing via a generic helper function? I.e., we already have bpf_get_current_pid_tgid(), why isn't that sufficient? Seems like adding it to the ctx doesn't scale as well to many prog types. If Linux does it in the ctx then cross-plat portability is a good reason to put it in the ctx, but I just checked the linux bpf_sock_addr and it is not there.

**Comment by saxena-anurag** [comment]
> Why add it to ctx instead of providing via a generic helper function? Seems like adding it to the ctx doesn't scale as well to many prog types. If Linux does it in the ctx then cross-plat portability is a good reason to put it in the ctx.

Since we are getting the process id from WFP metadata values, and this info is layer specific, even if we add a helper function, the helper function will not be generic and will be specific to these attach types (`BPF_CGROUP_INET*_CONNECT`, `BPF_CGROUP_INET*_RECV_ACCEPT`).

Regarding `bpf_get_current_pid_tgid()`, I am not sure if the value returned by this helper function will always be the process id of the app making the connect call / accepting the connection. If `bpf_get_current_pid_tgid()` returns the same value, then I agree we can use `bpf_get_current_pid_tgid()` and don't need to add `process_id` to `sock_addr_ctx`.

**Comment by dthaler** [comment]
> Regarding `bpf_get_current_pid_tgid()`, I am not sure if the value returned by this helper function will always be the process id of the app making the connect call / accepting the connection. If `bpf_get_current_pid_tgid()` returns the same value, then I agree we can use `bpf_get_current_pid_tgid()` and don't need to add `process_id` to `sock_addr_ctx`.

I think we should know the answer before approving this PR.

**Comment by saxena-anurag** [comment]
> 

Agree. I am trying to get that info.

**Comment by dthaler** [comment]
> > 
> 
> Agree. I am trying to get that info.

My understanding from the discussion on #1761 is that we will add a helper function instead of putting the process_id into the ctx, correct?

**Comment by saxena-anurag** [comment]
> > > 
> > 
> > 
> > Agree. I am trying to get that info.
> 
> My understanding from the discussion on #1761 is that we will add a helper function instead of putting the process_id into the ctx, correct?

Yes. Closing this PR now.

**Pull request closed without merging**
