### PR TITLE
Validate program type in ebpf_program_create

### PR DESCRIPTION
**Pull request by shpalani**
## Description

__ebpf_program_parameters had program_type not set. Hence the ebpf program failed to load and attach.

Behavior change in return value:
If the program type guid is 0, the new return value is changed 
    From:  EBPF_EXTENSION_FAILED_TO_LOAD
    To: EBPF_INVALID_ARGUMENT

Trace Addition:
1. This PR adds a trace for debugging where program type is 0.
2. This PR adds a trace for debugging to print the guid for program type and attach type. There can be cases when the extension can fail to load/attach:
    - Program type is valid but incorrect attach type (For eg, Program type is EBPF_PROGRAM_TYPE_BIND, Attach type is  EBPF_ATTACH_TYPE_XDP)
    - Attach type is valid but incorrect program type (For eg, EBPF_PROGRAM_TYPE_XDP, EBPF_ATTACH_TYPE_BIND)

## Testing

_Do any existing tests cover this change? Yes
Are new tests needed? No

Manual testing was done from ebpf-for-windows-demo using ebpf-for-window's ebpfcore changes, and collected the traces to verify.

PS C:\ebpf-for-windows-demo\Debug>  .\cilium_based_agent.exe --bpf-lb-mode=snat --device=ethernet
Initializing daemon with mode = snat
Using interface:
  name         = ethernet
  mtu          = 1500
  ifindex      = 8
  IPv4 address = 172.29.163.18

Cleaning up previous configuration ...
Compiling XDP eBPF program for SNAT ...
Verifying the program ...
Loading and attaching the program to XDP hook ...
bpf_object__load failed with error=-22
Failed to load and attach the XDP program, error = -22
PS C:\ebpf-for-windows-demo\Debug>
```
Logman trace:

{"Entry":"_ebpf_core_protocol_create_program","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericMessage","time":"2023-06-24T02:45:16.3382364Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":5,"opcode":1,"keywords":"0x1"}}
[1]1C10.1B78::2023/06/23-19:45:16.338237300 [EbpfForWindowsProvider]{"Entry":"ebpf_program_create_and_initialize","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericMessage","time":"2023-06-24T02:45:16.3382373Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":5,"opcode":1,"keywords":"0x1"}}
[1]1C10.1B78::2023/06/23-19:45:16.338238000 [EbpfForWindowsProvider]{"Entry":"ebpf_program_create","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericMessage","time":"2023-06-24T02:45:16.3382380Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":5,"opcode":1,"keywords":"0x1"}}
[1]1C10.1B78::2023/06/23-19:45:16.338239400 [EbpfForWindowsProvider]{"Message":"Program type must be specified.","*guid":"{00000000-0000-0000-0000-000000000000}","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericMessage","time":"2023-06-24T02:45:16.3382394Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x80"}}
[1]1C10.1B78::2023/06/23-19:45:16.338240300 [EbpfForWindowsProvider]{"ErrorMessage":"ebpf_program_create returned error","Error":6,"meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericError","time":"2023-06-24T02:45:16.3382403Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x2"}}
[1]1C10.1B78::2023/06/23-19:45:16.338245500 [EbpfForWindowsProvider]{"ErrorMessage":"ebpf_program_create_and_initialize returned error","Error":6,"meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericError","time":"2023-06-24T02:45:16.3382455Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x2"}}
[1]1C10.1B78::2023/06/23-19:45:16.338246200 [EbpfForWindowsProvider]{"ErrorMessage":"_ebpf_core_protocol_create_program returned error","Error":6,"meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericError","time":"2023-06-24T02:45:16.3382462Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x2"}}
[1]1C10.1B78::2023/06/23-19:45:16.338253800 [EbpfForWindowsProvider]{"Api":"\"ebpf_core_invoke_protocol_handler\"","status":"0xC000000D(NT=An invalid parameter was passed to a service or function.)","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfApiError","time":"2023-06-24T02:45:16.3382538Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x4"}}
[1]1C10.1B78::2023/06/23-19:45:16.338286400 [EbpfForWindowsProvider]{"Api":"DeviceIoControl","last_error":"87(WIN=The parameter is incorrect.)","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfApiError","time":"2023-06-24T02:45:16.3382864Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x100"}}
[1]1C10.1B78::2023/06/23-19:45:16.338287200 [EbpfForWindowsProvider]{"ErrorMessage":"invoke_ioctl returned error","Error":87,"meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericError","time":"2023-06-24T02:45:16.3382872Z","cpu":1,"pid":7184,"tid":7032,"channel":11,"level":2,"keywords":"0x4"}}
```

## Documentation

_Is there any documentation impact for this change? TSG (Trouble Shooting Guide) needs an addition of this trace. It will be addressed in #2625

### CODE REVIEW

**Comment by dthaler** [comment]
> ## Description
> __ebpf_program_parameters had program_type not set. Hence the ebpf program failed to load and attach.
> 
> ## Testing
> _Do any existing tests cover this change? Are new tests needed? No

I don't follow why "Are new tests needed" is a no.
This seems trivial to add a unit test to cover.

**Comment by shpalani** [comment]
> Are new tests needed" is a no.

Thanks for your comment. There is an existing test case with program_type set to 0. Updated the description.
TEST_CASE("EBPF_OPERATION_QUERY_PROGRAM_INFO", "[execution_context][negative]")

**Comment by dthaler** [comment]
> There is an existing test case with program_type set to 0. Updated the description. TEST_CASE("EBPF_OPERATION_QUERY_PROGRAM_INFO", "[execution_context][negative]")

Were we seeing CI/CD failures due to this issue?  If so, why is there no issue linked to this PR?  Or if not, then why isn't a test update needed?

**Comment by shpalani** [comment]
> Were we seeing CI/CD failures due to this issue?

Yes, there was a CI/CD failure reported. And I have updated the test case EBPF_OPERATION_QUERY_PROGRAM_INFO in the latest diff.

**Comment by dthaler** [comment]
> > Were we seeing CI/CD failures due to this issue?
> 
> Yes, there was a CI/CD failure reported.

Please link the issue # to the PR description.

**Review by dthaler — APPROVED** [review]

**Review by Alan-Jowett — APPROVED** [review]

**Pull request merged**
