### PR TITLE
Speedup ebpf_handle_table_terminate by avoiding acquire/release of lock

### PR DESCRIPTION
**Pull request by Alan-Jowett**
## Description

Replace calls to ebpf_handle_close, which acquired and released the handle table lock each time an emulated handle was closed, with a lock acquire and close on each valid handle.

## Testing

CI/CD

## Documentation

No.

## Installation

No.

### CODE REVIEW

**Review by mtfriesen — APPROVED** [review]

**Comment by Alan-Jowett** [comment]
Before:
image

After:
image
image

**Comment by mtfriesen** [comment]
> Before: image
> 
> After: image image

Wow - is this a unit test for this handle table specifically, or all unit tests are accelerated by this?

**Comment by Alan-Jowett** [comment]
> > Before: image
> > After: image image
> 
> Wow - is this a unit test for this handle table specifically, or all unit tests are accelerated by this?

This affects every single unit test, adding a few hundred ms delay to it. It ends up modifying thread priority and affinity 1024*2 times per each test, which adds up fast.

**Review by mikeagun — DISMISSED** [review]

**Review by dthaler — APPROVED** [review]

**Comment by dthaler** [comment]
@Alan-Jowett  please check unit test failure that caused this to be removed from the merge quee

**Review by dthaler — APPROVED** [review]

**Review by mikeagun — APPROVED** [review]

**Pull request merged**
